include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/features/circle/domain_old/**
    - lib/features/circle/data_old/**
    - lib/features/circle/presentation/provider_old/**
    - lib/features/circle/**/*_backup.dart
    - lib/core/widgets/*_backup.dart
    - scripts/seed.dart
